version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: n8n-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: n8n
    networks:
      - n8n-network
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-app
    restart: always
    volumes:
      - .data/n8n:/home/node/.n8n
      - .logs/n8n:/home/node/logs/n8n
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_DATABASE=n8n
      - DB_MYSQLDB_HOST=n8n-mysql
      - DB_MYSQLDB_PORT=3306
      - DB_MSYQLDB_USER=root
      - DB_MYSQLDB_PASSWORD=root
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - EXECUTIONS_PROCESS=main
      - N8N_METRICS=true
      - DB_LOGGING_OPTIONS=all
      - DB_LOGGING_ENABLED=true
      - N8N_LOG_OUTPUT=file
      - N8N_LOG_FILE_LOCATION=/home/node/logs/n8n/n8n.log
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge